### PR TITLE
fix libghdl version

### PR DESCRIPTION
**Pull request by eine**
After releasing `v0.37`, the new development version is `0.1.dev0`.

https://github.com/ghdl/docker/runs/476046544?check_suite_focus=true

### CODE REVIEW

**Comment by tgingold** [comment]
Thanks!

**Comment by eine** [comment]
I'm so sorry, but I did a stupid mistake. The new version is `1.0.dev0`, NOT `0.1.dev0`. @tgingold, can you change it directly or should I open another PR?

**Comment by tgingold** [comment]
Fixed.

**Comment by eine** [comment]
Thanks! All green again: https://github.com/ghdl/docker/runs/478119483

**Pull request merged**
